# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhjYHv0VqKH1d3CDtcG2ZeLTDyhSC1lE
"""

print("seja muito bem vindo ao sistema automatizado de vendas")

LIMITE_DE_SEGURANÇA = 5000



# COLETAR VALOR DAS 3 VENDAS

Venda1 = float(input("valor da venda 1:"))

Venda2 = float(input("valor da venda 2:"))

Venda3 = float(input("valor da venda 3:"))



# FAZER MEDIA DAS VENDAS

def analise_de_vendas():

 global LIMITE_DE_SEGURANÇA

 media = (Venda1+Venda2+Venda3) / 3

 print(f"A media das vendas é equivalente a: {media}")

 return media



media_das_vendas = analise_de_vendas()



resposta_valida = ("sim","não")

legitimo = input("A venda é legitima? (sim/não)")



while legitimo not in resposta_valida:

 print("Resposta invalida.")

 legitimo = input("A venda é legitimo (sim/não)")



if legitimo == "sim":

 print("Aprovado")

elif legitimo == "não":

 LIMITE_DE_SEGURANÇA = float(input("Qual deve ser o novo valor sugerido?"))

 print(f"Aprovado! o valor do limite de segurança foi alterado para R${LIMITE_DE_SEGURANÇA}")

else:

 print("Valor invalido")



if legitimo == "não" and media_das_vendas >= LIMITE_DE_SEGURANÇA:

  print("Sistema em quarentena")

else:

  print("Vendas normais")



if Venda1 >= media_das_vendas * 5 or Venda2 >= media_das_vendas * 5 or Venda3 >= media_das_vendas * 5:

 print("REVISÃO MANUAL")



print("="*50)



print(f"Tipo de variavel de venda1: {type(Venda1)}")

print(f"Tipo de variavel de venda2: {type(Venda2)}")

print(f"Tipo de variavel de venda3: {type(Venda3)}")

print(f"Tipo de variavel de media_das_vendas:{type(media_das_vendas)}")

print(f"Tipo de variavel de LIMITE_DE_SEGURANÇA:{type(LIMITE_DE_SEGURANÇA)}")